version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_microservices
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - microservices_network

volumes:
  mysql_data:

networks:
  microservices_network:
    driver: bridge
